/*
EXAMEN BASE DE DATOS SQL RETO INDUSTRIAL
DESARROLLO RETO 2025
LIDER: BENJAMIN RESENDIZ MEJIA
RESUELVE: DANIEL JIMENEZ ALCANTAR
FECHA : 02-05-20255
*/
/*Inserción de datos*/
-- Zonas
INSERT INTO ZONA (DESCRIPCION) VALUES ('DEL VALLE'), ('NARVARTE');

-- Áreas
INSERT INTO AREA (DESCRIPCION) VALUES ('SISTEMAS'), ('ADMINISTRACIÓN');

-- Puestos
INSERT INTO PUESTO (DESCRIPCION) VALUES ('COORDINADOR'), ('ANALISTA'), ('PROGRAMADOR');

-- Alumnos
INSERT INTO ALUMNOS (LOGIN, AREA, ZONA, PUESTO, NOMBRE) VALUES
(1001, 1, 1, 1, 'Ana Torres'),
(1002, 2, 1, 2, 'Luis Pérez'),
(1003, 1, 2, 1, 'Marta León'),
(1004, 1, 2, 3, 'Raúl Gómez');

-- 3.1 MOSTRAR A TODOS LOS COORDINADORES
SELECT * FROM ALUMNOS A
JOIN PUESTO P ON A.PUESTO = P.IDPUESTO
WHERE P.DESCRIPCION = 'COORDINADOR';

-- 3.2 MOSTRAR A TODAS LAS PERSONAS QUE LABOREN EN LA ZONA DEL VALLE
SELECT * FROM ALUMNOS A
JOIN ZONA Z ON A.ZONA = Z.IDZONA
WHERE Z.DESCRIPCION = 'DEL VALLE';

-- 3.3 MOSTRAR A TODOS LOS EMPLEADOS QUE LABOREN EN LA ZONA NARVARTE
SELECT * FROM ALUMNOS A
JOIN ZONA Z ON A.ZONA = Z.IDZONA
WHERE Z.DESCRIPCION = 'NARVARTE';

-- 3.4 AGRUPAR TODAS LAS PERSONAS POR AREA
SELECT AR.DESCRIPCION AS AREA, COUNT(*) AS TOTAL_PERSONAS
FROM ALUMNOS A
JOIN AREA AR ON A.AREA = AR.IDAREA
GROUP BY AR.DESCRIPCION;

-- 3.5 CRUCE COMPLETO (UNIÓN DE TABLAS)
SELECT A.LOGIN, A.NOMBRE, AR.DESCRIPCION AS AREA, Z.DESCRIPCION AS ZONA, P.DESCRIPCION AS PUESTO
FROM ALUMNOS A
JOIN AREA AR ON A.AREA = AR.IDAREA
JOIN ZONA Z ON A.ZONA = Z.IDZONA
JOIN PUESTO P ON A.PUESTO = P.IDPUESTO;