/*
EXAMEN BASE DE DATOS SQL RETO INDUSTRIAL
DESARROLLO RETO 2025
LIDER: BENJAMIN RESENDIZ MEJIA
RESUELVE: DANIEL JIMENEZ ALCANTAR
FECHA : 02-05-20255

1. CREAR UNA BASE DE DATOS LLAMADA PERSONAL
2. CREAR LAS SIGUIENTES TABLAS DENTRO DE LA BASE:
*/

CREATE DATABASE IF NOT EXISTS PERSONAL;
USE PERSONAL;

-- Tabla ALUMNOS (PERSONAS)
CREATE TABLE ALUMNOS (
  LOGIN INT PRIMARY KEY,
  AREA INT,
  ZONA INT,
  PUESTO INT,
  NOMBRE VARCHAR(100) NOT NULL,
  FOREIGN KEY (AREA) REFERENCES AREA(IDAREA),
  FOREIGN KEY (ZONA) REFERENCES ZONA(IDZONA),
  FOREIGN KEY (PUESTO) REFERENCES PUESTO(IDPUESTO)
);
/*CREAR TABLA DE ALUMNOS*/
CREATE TABLE AREA (
  IDAREA INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCION VARCHAR(50) NOT NULL
);

-- Tabla ZONA
CREATE TABLE ZONA (
  IDZONA INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCION VARCHAR(50) NOT NULL
);

-- Tabla PUESTO
CREATE TABLE PUESTO (
  IDPUESTO INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCION VARCHAR(50) NOT NULL
);

