 /*Procedimiento almacenado*/

/*Procedmiento almacenado para obtener  Personas por zona*/

CREATE PROCEDURE SP_PERSONAS_POR_ZONA(IN IDZONA_IN INT)
BEGIN
  SELECT A.LOGIN, A.NOMBRE, Z.DESCRIPCION AS ZONA
  FROM ALUMNOS A
  JOIN ZONA Z ON A.ZONA = Z.IDZONA
  WHERE Z.IDZONA = IDZONA_IN;
END 
-- Procedmiento almacenado para obtener personas por puesto

CREATE PROCEDURE SP_PERSONAS_POR_PUESTO(IN PUESTO_IN INT)
BEGIN
  SELECT A.LOGIN, A.NOMBRE, P.DESCRIPCION AS PUESTO
  FROM ALUMNOS A
  JOIN PUESTO P ON A.PUESTO = P.IDPUESTO
  WHERE P.IDPUESTO = PUESTO_IN;
END 
-- Procedmiento almacenado para obtener cruce general
CREATE PROCEDURE SP_CRUCE_GENERAL()
BEGIN
  SELECT A.LOGIN, A.NOMBRE, AR.DESCRIPCION AS AREA, Z.DESCRIPCION AS ZONA, P.DESCRIPCION AS PUESTO
  FROM ALUMNOS A
  JOIN AREA AR ON A.AREA = AR.IDAREA
  JOIN ZONA Z ON A.ZONA = Z.IDZONA
  JOIN PUESTO P ON A.PUESTO = P.IDPUESTO;
END 